/* generated by tools/mkassets.py */
#pragma once
#include "lvgl.h"

extern const lv_image_dsc_t app_icon_mouse;
extern const lv_image_dsc_t app_icon_clock;
extern const lv_image_dsc_t app_icon_timer;
extern const lv_image_dsc_t app_icon_keys;
extern const lv_image_dsc_t app_icon_type;
extern const lv_image_dsc_t app_icon_present;
extern const lv_image_dsc_t app_icon_calc;
extern const lv_image_dsc_t app_icon_games;
extern const lv_image_dsc_t app_icon_meet;
extern const lv_image_dsc_t icon_gear;


