/* Generated by tools/mkfonts.py. Do not edit by hand.
 *
 * 🚨 One font per size the interface draws Chinese at. Each falls back
 *    to the Montserrat of the same size for everything it does not
 *    carry — Latin, digits, punctuation and the LV_SYMBOL_* glyphs —
 *    so a single label may mix the two freely. */
#pragma once
#include "lvgl.h"

extern const lv_font_t font_zh_14;
extern const lv_font_t font_zh_16;
extern const lv_font_t font_zh_18;
extern const lv_font_t font_zh_20;
extern const lv_font_t font_zh_24;
extern const lv_font_t font_zh_26;
extern const lv_font_t font_zh_18_bold;

